version: '3.8'
name: domino_parejas_individual

services:
  app:
    container_name: domino_parejas_individual
    image: joanalba/domino_parejas_individual:latest
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "80:80"
      - "8000:8000"
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets:/app/secrets
    environment:
      - POSTGRES_USER_FILE=/app/secrets/postgres_user.txt
      - POSTGRES_PASSWORD_FILE=/app/secrets/postgres_password.txt
      - POSTGRES_DB_FILE=/app/secrets/postgres_db.txt
      - SECRET_KEY_FILE=/app/secrets/secret_key.txt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
    name: domino_parejas_individual_db_data 